// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvX5FbvdLc29-5loKXNE9YGo2VWr0QUZ8',
    appId: '1:467610928095:android:edfba629700f1a4973ba6a',
    messagingSenderId: '467610928095',
    projectId: 'aic-woippy-app-8815b',
    storageBucket: 'aic-woippy-app-8815b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJIEH4IehuSkJf79LyAhw3q7XDYfijoo4',
    appId: '1:467610928095:ios:ae163769cf02235073ba6a',
    messagingSenderId: '467610928095',
    projectId: 'aic-woippy-app-8815b',
    storageBucket: 'aic-woippy-app-8815b.firebasestorage.app',
    iosBundleId: 'com.aicwoippy.aicWoippyApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxZ7C1X_iv3f94D7vVIpchmiW_VjSYPXA',
    appId: '1:467610928095:web:8121fc4f8341cfb273ba6a',
    messagingSenderId: '467610928095',
    projectId: 'aic-woippy-app-8815b',
    authDomain: 'aic-woippy-app-8815b.firebaseapp.com',
    storageBucket: 'aic-woippy-app-8815b.firebasestorage.app',
    measurementId: 'G-JSQRTF7DPG',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJIEH4IehuSkJf79LyAhw3q7XDYfijoo4',
    appId: '1:467610928095:ios:ae163769cf02235073ba6a',
    messagingSenderId: '467610928095',
    projectId: 'aic-woippy-app-8815b',
    storageBucket: 'aic-woippy-app-8815b.firebasestorage.app',
    iosBundleId: 'com.aicwoippy.aicWoippyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxZ7C1X_iv3f94D7vVIpchmiW_VjSYPXA',
    appId: '1:467610928095:web:7735122335dc7c6b73ba6a',
    messagingSenderId: '467610928095',
    projectId: 'aic-woippy-app-8815b',
    authDomain: 'aic-woippy-app-8815b.firebaseapp.com',
    storageBucket: 'aic-woippy-app-8815b.firebasestorage.app',
    measurementId: 'G-RGE1G50W4H',
  );

}